version: "3.7"
services:
  
  rtriqc_db:
    container_name: rtriqc_db
    restart: unless-stopped
    ports:
     - "3336:3306"
    build:
      context: ./
      dockerfile: docker-compose/mysql/Dockerfile
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: rtriqc_mysql
    volumes:
      - rtriqc_mysql:/var/lib/mysql
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d

  rtriqc_app:
    build:
      args:
        user: bbett
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: rtriqc_app
    container_name: rtriqc_app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
   
  rtriqc_nginx:
    container_name: rtriqc_nginx
    restart: unless-stopped
    ports:
      - 8094:80
    build:
        context: ./
        dockerfile: docker-compose/nginx/Dockerfile
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx/:/etc/nginx/conf.d/

volumes:
  rtriqc_mysql: